# Generated by Django 3.1.1 on 2020-11-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloge',
            new_name='Blog',
        ),
    ]
